### ISSUE TITLE
busybox error

### ISSUE THREAD

**Issue by shams75** [Hax4us/TermuxAlpine#1] opened 2018-03-06 13:14 UTC
Executing busybox-1.27.2-r8.trigger
ERROR: busybox-1.27.2-r8.trigger: script exited with error 127
3 errors; 101 MiB in 32 packages

**Comment by EsdrasTarsis** [comment] 2018-04-07 21:49
This problem also occurs in the ca-certificates package.

**Comment by pts** [comment] 2018-04-27 12:46
I'm also getting this error. How can this be debugged? Is there way to make `apk` show the real error message?

**Comment by pts** [comment] 2018-04-27 13:01
It looks like the trigger script works fine when executed manually:

```
# tar xvf scripts.tar busybox-1.27.2-r7.Q16KKkDenzjdRkzTB/WOw1mNRvBYo=.trigger
busybox-1.27.2-r7.Q16KKkDenzjdRkzTB/WOw1mNRvBYo=.trigger
# cat busybox-1.27.2-r7.Q16KKkDenzjdRkzTB/
cat: read error: Is a directory
# cat busybox-1.27.2-r7.Q16KKkDenzjdRkzTB/WOw1mNRvBYo\=.trigger 
#!/bin/sh

do_bb_install=

for i in "$@"; do
        case "$i" in
                /lib/modules/*)
                        if [ -d "$i" ]; then
                                /bin/busybox depmod ${i#/lib/modules/}
                        fi
                        ;;
                *) do_bb_install=yes;;
        esac
done

if [ -n "$do_bb_install" ]; then
        [ -e /bin/bbsuid ] && /bin/bbsuid --install
        [ -e /bin/busybox-extras ] && /bin/busybox-extras --install -s
        /bin/busybox --install -s
fi
# busybox-1.27.2-r7.Q16KKkDenzjdRkzTB/WOw1mNRvBYo\=.trigger  x          
# echo $?
0
```

So why does apk fail when executing this script?

**Comment by Hax4us** [comment] 2018-05-26 13:01
Finally I found the root cause and the problem is in proot so I will give a PR to proot and this problem will be solved after my PR merge

**Comment by Hax4us** [comment] 2018-05-26 13:30
https://github.com/termux/proot/pull/17

**Comment by Hax4us** [comment] 2018-05-29 09:26
My PR is merged now and just upgrade your proot and reinstall Alpine

**Closed by Hax4us** 2018-05-29 09:26 UTC

**Comment by grind086** [comment] 2018-06-01 00:15
I'm still getting this error even though I have the new version of proot according to termux/termux-packages#2464 (revision 10)

```
$ apt install proot
Reading package lists... Done
Building dependency tree
Reading state information... Done
proot is already the newest version (5.1.107-10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

I've done a fresh install of everything including termux itself. Any suggestions?

**Comment by gauloics** [comment] 2018-09-20 07:43
I'm also still getting this error 😭

**Comment by probonopd** [comment] 2019-10-23 06:48
I am running into what looks like a similar error, but unrelated to Termux (I am not using it): https://github.com/proot-me/proot/issues/191.
